

# Helper to generate sender JSON
def generate_sender_json(user_details):
    return {
        "name": user_details["name"],
        "firstName": user_details["name"],
        "lastName": user_details["surname"],
        "company": "",
        "phone": user_details["phoneNumber"],
        "address": user_details["address1"],
        "address2": user_details["address2"],
        "city": user_details["city"],
        "state": user_details["state"],
        "postalCode": user_details["zipCode"],
        "country": user_details["country"],
        "isResidential": user_details["isResidentialAddress"],
        "isDeleted": "false",
        "fullAddress": f'{user_details["address1"]} {user_details["address2"]} {user_details["city"]} {user_details["state"]} {user_details["zipCode"]} {user_details["country"]}'
    }


sender_json_template = {
                "name": "",
                "firstName": "",
                "lastName": "",
                "company": "",
                "phone": "",
                "address": "",
                "address2": "",
                "city": "",
                "state": "",
                "postalCode": "",
                "country": "",
                "isResidential": "false",
                "isMilitaryBox": "false",
                "latitude": 0.0,
                "longitude": 0.0,
                "isDeleted": "true",
                "isInternational": "false",
                "fullAddress": "",
            }
receiver_json = {
                "name": "",
                "firstName": "",
                "lastName": "",
                "company": "",
                "phone": "",
                "address": "",
                "address2": "",
                "city": "",
                "state": "",
                "postalCode": "",
                "country": "",
                "isResidential": "false",
                "isMilitaryBox": "false",
                "latitude": 0.0,
                "longitude": 0.0,
                "isDeleted": "true",
                "isInternational": "false",
                "fullAddress": "",
            }

sender_json = {
                "name": "",
                "firstName": "",
                "lastName": "",
                "company": "",
                "phone": "",
                "address": "",
                "address2": "",
                "city": "",
                "state": "",
                "postalCode": "",
                "country": "",
                "isResidential": "false",
                "isMilitaryBox": "false",
                "latitude": 0.0,
                "longitude": 0.0,
                "isDeleted": "true",
                "isInternational": "false",
                "fullAddress": "",
            }

package_details_json = {    
    "externalTrackingNumber": "",
    "insuredValue": 0,
    "insuranceQuoteId": None,
    "type": 0,
    "weightOunces": 0,
    "unitOfDimension": 1,
    "unitOfWeight": 3,
    "length": 0,
    "width": 0,
    "height": 0,
    "bagSizeId": 0,
    "useOfKaeboxBags": True,
    "serviceTypes": [],
    "shippingLabelUrl": "",
    "deliveryType": 1,
    "beforePickupImageId": None,
    "packageNumber": None,
    "indications": [0],
    "parcelShipping": None,
    "deliveryInstructions": 0,
    "deliveryPin": 0,
    "customsDeclaration": None,
    "printYourOwnLabel": True,
    "Confirmed":False
}

num_package_details_json = {    
    "externalTrackingNumber": "",
    "insuredValue": 0,
    "insuranceQuoteId": None,
    "type": 0,
    "weightOunces": 0,
    "unitOfDimension": 1,
    "unitOfWeight": 3,
    "length": 0,
    "width": 0,
    "height": 0,
    "bagSizeId": 0,
    "useOfKaeboxBags": True,
    "serviceTypes": [],
    "shippingLabelUrl": "",
    "deliveryType": 1,
    "beforePickupImageId": None,
    "packageNumber": None,
    "indications": [0],
    "parcelShipping": None,
    "deliveryInstructions": 0,
    "deliveryPin": 0,
    "customsDeclaration": None,
    "printYourOwnLabel": True,
    "Confirmed":False
}
